# Generated by Django 3.2.5 on 2021-07-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.TextField(max_length=150),
        ),
    ]
